# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Quest APK Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+
      - v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+-[0-9a-zA-Z]+
env:
 FHIRCORE_USERNAME: ${{ secrets.FHIRCORE_USERNAME }}
 FHIRCORE_ACCESS_TOKEN: ${{ secrets.FHIRCORE_ACCESS_TOKEN }}
 CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
 KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
 KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
 KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - name: Decode Keystore file
        run: echo $ENCODED_KEYSTORE | base64 -di > "${HOME}"/fhircore.keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}
      
      - name: Generate local.properties file
        run: echo $LOCAL_PROPERTIES > local.properties
        working-directory: android
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}    

      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: android
 
      - name: Spotless check quest application
        run: ./gradlew :quest:spotlessCheck
        working-directory: android

      - name: Generate AAB (Android App Bundle) file
        if: ${{ false }}
        run: ./gradlew :quest:bundleRelease -x :quest:testDebugUnitTest --stacktrace
        working-directory: android
        
      - name: Upload AAB file to tag assets
        if: ${{ false }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/quest/build/outputs/bundle/release/quest-release.aab
          asset_name: "quest-$tag.aab"
          tag: ${{ github.ref }}
          overwrite: true
      
      - name: Generate APK (Android App PacKage) file
        run: ./gradlew :quest:assembleRelease -x :quest:testDebugUnitTest --stacktrace
        working-directory: android
        
      - name: Upload APK file to tag assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/quest/build/outputs/apk/release/quest-release.apk
          asset_name: "quest-$tag.apk"
          tag: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
          overwrite: true
